Fix "Multiple assets emit..." for webpack@4.40.x
The latest webpack update broke the @mdi/font package in build time.
Webpack devops added check for duplicate depending assets and throws error:
Error: Conflict: Multiple assets emit to the same filename 1993c4a16cce5446a5cfafacf4da740b.eot